### ISSUE TITLE
Speakers and Presenters page needed

### ISSUE THREAD

**Issue by tamaramunzner** [hdc-arizona/ieeevis.org#4]
Currently link goes to the video previews page, that's not right.

**Comment by cscheid** [comment]
You're right - that's a bug in the sidebar. But there's not a lot of content in the [page itself](http://ieeevis.org/year/2016/info/presenter-information/speakers-and-presenters). What do we do about that

**Comment by cscheid** [comment]
- [x] Fix sidebar
- [ ] Make sure the content is correct.

**Comment by tamaramunzner** [comment]
1. Carlos has the (very reasonable) position that he never makes content
   decisions. So the question is who is the "owner" of that page and should
   figure out what to put there. It's not squarely in any chair's job, it
   crosses over between many roles.

Thus I add a few possible people who might have thoughts on this into this
discussion including Nicole and Gautam.
1. Nicole, adding you to the discussion since you've been liaising with the
   AV folks. I note there's a bunch of information on last year's page that we
   might want to migrate but it certainly needs fact checking first,
   especially since we are changing companies.

http://ieeevis.org/year/2015/info/presenter-information/speakers-and-presenters
1. My own suggestions for that page:

Start with a section heading "Timing" and put this sentence there:

*Presenters are expected to arrive to their session 15 minutes early *to
meet their session chair and receive final instructions.

Then a section called "Slides"

where you say

"To gain maximum size and benefit on the screen, we encourage speakers to
utilize the 16x9 format for their slides." and then have a link to the
PowerPoint templates as

"Powerpoint template files: [LINK: light background], [LINK: dark
background]"

Then have a section headed "Hardware" with all that other stuff about the
AV hardware setup, after a fact check pass.

We should also add some kind of information about a Speaker Prep room (if
it exists this year) to this blurb. Gautam, I put that in your lap.

**Comment by cscheid** [comment]
This is great, Tamara, thanks. It's also a good opportunity for me to show you two new features of the system we'll be moving to soon.

# Points of contact

For example, if you go to the [workshops page](https://github.com/hdc-arizona/ieeevis.org/blob/master/year/2016/info/overview-amp-topics/workshops.md) and click "Raw", you'll see something like this:

```
---
title: Workshops
layout: main
permalink: /year/2016/info/overview-amp-topics/workshops
contact: "workshops@ieeevis.org"
---
```

The "contact" field is meant to be the email of the person (or team) primarily responsible for the page. This is so that if there's a problem there, we know directly who to contact. If you look at the "staging" version of the vis webpage, http://staging.ieeevis.com,  (for example, [this is the workshops page on the staging server](http://staging.ieeevis.com/year/2016/info/overview-amp-topics/workshops)] you'll see that at the bottom of the page there's a note that says: "Problems with this webpage? contact workshops@ieeevis.org." The hope is that this will bring added clarity about who's responsible for what. (By default, pages without contact information get sent to web@ieeevis.org).

# Easy editing of content

In addition, if anyone wants to take a crack at editing content, they can go to the github page (using the [workshops page again as an example](https://github.com/hdc-arizona/ieeevis.org/blob/master/year/2016/info/overview-amp-topics/workshops.md)), and click on the pencil icon: that stands for "edit". This will fire off GitHub's web-based editor. Once the content is saved, it creates a pull request which I will be able to merge and incorporate to the main page.

**Comment by cscheid** [comment]
If anyone wants to take a crack at editing the speakers and presenters page, they can [click here](https://github.com/hdc-arizona/ieeevis.org/blob/master/year/2016/info/presenter-information/speakers-and-presenters.md), click the edit button (_that's the pencil icon_) and take it from there.

**Comment by tamaramunzner** [comment]
Adding Jesus and Terry too.

**Comment by tamaramunzner** [comment]
Just fyi, contents of this page was verified with the new AV company and is
online now.

http://ieeevis.org/year/2016/info/presenter-information/speakers-and-presenters

Cheers,

## Gautam.

**Comment by cscheid** [comment]
We're moving the repo under the [ieee-vgtc organization](http://github.com/ieee-vgtc/ieeevis.org). Closing this issue for now.
